Fix Alpine Linux pkg conflict
The cdrkit and xorriso are conflicting, so remove the latter.

ERROR: unable to select packages:
  cdrkit-1.1.11-r3:
    conflicts: xorriso-1.5.4-r2[cmd:mkisofs=1.1.11-r3]
    satisfies: world[cdrkit]
  xorriso-1.5.4-r2:
    conflicts: cdrkit-1.1.11-r3[cmd:mkisofs=1.5.4-r2]
    satisfies: world[xorriso]

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>